"""Job spec: the JSON n8n sends to this repo. Lenient on purpose (extra keys allowed)."""
from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import BaseModel, ConfigDict, Field


class _Base(BaseModel):
    model_config = ConfigDict(extra="allow")


class Word(_Base):
    w: str
    start: float
    end: float


class Voiceover(_Base):
    url: Optional[str] = None          # ready-made audio ...
    path: Optional[str] = None
    gain: float = 1.0
    words: list[Word] = Field(default_factory=list)  # ... + word timestamps -> captions
    # OR let this repo narrate: send the script and it calls your Chatterbox TTS (Modal)
    script: Optional[str] = None
    voice: Optional[str] = None
    exaggeration: float = 0.5
    repetition_penalty: float = 1.5
    speed: float = 1.0
    pause_after_ms: Optional[list] = None
    exaggerations: Optional[list] = None
    strict_short_sentences: bool = False


class Music(_Base):
    url: Optional[str] = None
    path: Optional[str] = None
    gain: Optional[float] = None


class Popup(_Base):
    text: str
    at: Optional[float] = None     # absolute seconds; OR use word/offset (resolved against the narration)
    word: Optional[str] = None     # spoken keyword in this scene -> pop-up lands exactly on it
    offset: float = 0.3            # seconds after scene start (used when no at/word)
    duration: float = 1.3
    style: str = "pop"             # pop | slide | stamp
    position: str = "center"       # top | center | bottom
    color: Optional[str] = None


class SfxCue(_Base):
    query: Optional[str] = None    # "whoosh", "heavy impact", ...
    id: Optional[str] = None       # exact library id (wins over query)
    at: Optional[float] = None     # absolute seconds; OR word/offset like popups
    word: Optional[str] = None
    offset: float = 0.0
    gain: float = 0.8
    align: str = "onset"           # onset (sound starts at cue) | peak (loudest hit lands on cue) | end (sound ends at cue)
    dur: Optional[float] = None    # max seconds to play from the cue (cut + fade); default = until the scene ends


class Visual(_Base):
    type: str = "text"             # image | text | none
    url: Optional[str] = None
    path: Optional[str] = None
    text: Optional[str] = None     # for type=text (defaults to the scene text)
    prompt: Optional[str] = None   # for type=image without url/path: generated by your image model (batched)
    characters: Optional[list[str]] = None   # registered character names (e.g. ["Leo","Mia"]) -> sent as character_names
    motion: Optional[str] = None   # zoom_in zoom_out pan_left pan_right float shake push none
    fit: str = "cover"


class Scene(_Base):
    id: Optional[str] = None
    start: Optional[float] = None   # omit when voiceover.script is used (timing comes from the narration)
    end: Optional[float] = None
    text: str = ""
    visual: Visual = Field(default_factory=Visual)
    popups: list[Popup] = Field(default_factory=list)
    sfx: list[SfxCue] = Field(default_factory=list)
    transition: Optional[str] = None            # cut fade whip zoom flash
    character: Optional[Union[bool, str, dict]] = None  # True | "pose" | {"pose","side","action"}


class Job(_Base):
    job_id: str = "job"
    channel: str = "default"
    format: dict[str, Any] = Field(default_factory=dict)   # width/height/fps
    aspect: Optional[str] = None               # "9:16" | "16:9" | "1:1" | "4:5" ...
    resolution: Optional[Any] = None           # short side: 720 | "1080p" | "4k"
    duration: Optional[float] = None
    voiceover: Optional[Voiceover] = None
    music: Optional[Music] = None
    scenes: list[Scene]
    captions: Optional[dict[str, Any]] = None   # per-job caption overrides
    style: dict[str, Any] = Field(default_factory=dict)    # deep-merged over the channel profile
    output: dict[str, Any] = Field(default_factory=dict)   # {"filename": "...", "upload": true}
    callback_url: Optional[str] = None          # n8n webhook, POSTed when finished
